version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    entrypoint: [ "sh", "-c", "sleep 10 && java -jar /app.jar --spring.profiles.active=docker" ]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=shop_admin
      - SPRING_DATASOURCE_PASSWORD=passpass
    networks:
      - runshop-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shop
      MYSQL_USER: shop_admin
      MYSQL_PASSWORD: passpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - runshop-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql" ]
      interval: 3s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - runshop-network

networks:
  runshop-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
