services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=shop_admin
      - SPRING_DATASOURCE_PASSWORD=passpass
    networks:
      - runshop-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: shop
      MYSQL_USER: shop_admin
      MYSQL_PASSWORD: passpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql  # 경로 수정
    networks:
      - runshop-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 3s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - runshop-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - runshop-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - runshop-network
    depends_on:
      - prometheus
    volumes:
      - ./grafana-data:/var/lib/grafana

networks:
  runshop-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
