spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 60000  # ?? ?? ?? (ms)
      cache-null-values: false
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbal  # JWT 비밀 키 추가

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
---
---
# ?? ?? ???? (dev)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb  # 메모리 모드 사용
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    # Redis ?? - ????? localhost ??
  data:
    redis:
      host: localhost
      port: 6379


  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbal  # JWT 비밀 키 추가

---
---
# Docker
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: shop_admin
    password: passpass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Redis ?? - Docker??? ???? ?? 'redis' ??
  data:
    redis:
      host: redis
      port: 6379

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbal  # ??? ?? JWT ?? ?? ????
---
---
# ??? ???? (test)
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb  # 메모리 모드 사용
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  # Redis ?? - ??? ????? ??? ?? localhost ??
  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbal  # ??? ?? JWT ?? ?? ????

